name: Maven Build
on:
  push:

jobs:
  build: 
    runs-on: ubuntu-latest
    permissions: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with: 
        distribution: adopt
        java-version: 21
        cache: maven

    - name: Build
      run: mvn -B package --file pom.xml
