name: Java CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        java-version: [21]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with: 
        distribution: 'adopt'
        java-version: ${{ matrix.java-version }}

    - name: Run tests
      run: mvn test

    - name: Build with Maven
      run: mvn clean install